AWSTemplateFormatVersion: '2010-09-09'
Description: 'Finding the Rock LMS - Minimal Setup'

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${Environment}-lms-users'
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub '${Environment}-lms-client'
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH

  # S3 Bucket
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Environment}-lms-content-${AWS::AccountId}'
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE]
            AllowedOrigins: ['*']
            MaxAge: 3000

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: !Sub '${Environment}-user-pool-id'
  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${Environment}-user-pool-client-id'
  ContentBucketName:
    Value: !Ref ContentBucket
    Export:
      Name: !Sub '${Environment}-content-bucket'